aiven/pghoard/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,53 +1,81 @@
+name: Build pghoard
+
 on:
   push:
-    branches: main
-  pull_request: {}
+    branches:
+      - main
+    tags:
+      - '**'
+  pull_request:
 
-name: CI
 jobs:
 
-  test-software:
+  lint:
     runs-on: ubuntu-latest
     strategy:
       matrix:
+        # only use one version for the lint step
         python-version: ["3.9"]
+
     steps:
-      - name: Check out source code
+
+      - id: checkout-code
         uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - name: Set up Python
+
+      - id: prepare-python
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip setuptools wheel
-          python -m pip install git+https://github.com/nmigen/nmigen.git
-      - name: Install software
-        run: python -m pip install -e ./software[toolchain]
-      - name: Run tests
-        working-directory: ./software
-        env:
-          YOSYS: yowasp-yosys
-          NEXTPNR_ICE40: yowasp-nextpnr-ice40
-          ICEPACK: yowasp-icepack
-        run: python -W ignore::DeprecationWarning test.py -v
 
-  build-firmware:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out source code
-        uses: actions/checkout@v2
-        with:
-          submodules: recursive
-      - name: Install dependencies
+      - id: dependencies
         run: |
+          pip install -r requirements.txt
+          pip install -r requirements.dev.txt
+
+      - id: pylint
+        run: make lint
+
+      - id: validate-style
+        run: |
+          make fmt
+          if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
+            echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2;
+            git diff;
+            exit 1;
+          fi
+
+  test:
+    runs-on: ubuntu-latest
+    needs: lint
+    strategy:
+      max-parallel: 4
+      matrix:
+        python-version: ["3.9"]
+        pg-version: [9.6, 10, 11, 12]
+
+    steps:
+      - id: checkout-code
+        uses: actions/checkout@v2
+
+      - id: prepare-python
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - id: dependencies
+        run: |
+          # Setup the Postgres repositories
+          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
+          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
           sudo apt-get update
-          sudo apt-get install sdcc
-      - name: Build libfx2
-        working-directory: ./vendor/libfx2/firmware
-        run: make
-      - name: Build firmware
-        working-directory: ./firmware
-        run: make
+          # Setup build deps
+          sudo apt-get install -y libsnappy-dev
+          sudo apt-get install -y postgresql-${{ matrix.pg-version }}
+          # Setup common python dependencies
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install --upgrade -r requirements.dev.txt
+          pip install -e .
+
+      - id: unittest
+        run: make unittest
