clalancette/oz/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,54 +1,41 @@
-name: Build
+---
+name: Run CI checks
 
-on:
-  schedule:
-    - cron: "0 12 * * SUN"
-  pull_request:
-    branches:
-     -  '*'
-  push:
-    branches:
-      - "*"
-
+on: [pull_request]
 
 jobs:
-  build:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        python-version: ["3.9"]
-        os: [ubuntu-latest, macos-latest]
+  unittests-fedora:
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Decrypt large secret
-        run: ./.github/scripts/decrypt_secrets.sh
-        env:
-          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}
-
-      - name: Copying Config.yml to random_word folder
-        run: cp $HOME/secrets/config.yml random_word/
-
-      - name: Print Directory Structure of random_word
-        run: ls -la random_word
-
-      - name: Setup Python
-        uses: actions/setup-python@v2
+      - name: Checkout the repo
+        uses: actions/checkout@v4
         with:
-          python-version: ${{ matrix.python-version }}
-          architecture: x64
-
-      - name: Install packages
-        run: |
-            pip install pipenv
-            pip install autopep8
-            pip install nose
-            pipenv install
-            pipenv run python setup.py install
-      
-      - name: Python Lint
-        run: |
-          make lint
-
-      - name: Run tests
-        run: |
-          pipenv run nosetests
+          fetch-depth: 0
+      - name: Install required packages
+        run: sudo apt-get install make flake8 pylint
+      # it's not in Ubuntu 22.04, was added in 23.04
+      - name: Install diff-cover from pip
+        run: pip install diff-cover
+      - name: Run the tests
+        run: sudo make container-unittests-fedora
+      - name: Run diff-cover
+        run: diff-cover coverage.xml  --compare-branch=origin/$GITHUB_BASE_REF --fail-under=90
+      - name: Run diff-quality (pylint)
+        # we want to run this regardless of whether previous lint steps failed
+        if: success() || failure()
+        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=pylint --fail-under=90
+      - name: Run diff-quality (flake8)
+        # we want to run this regardless of whether previous lint steps failed
+        if: success() || failure()
+        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=flake8 --fail-under=90
+  unittests-el7:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Install make
+        run: sudo apt-get install make
+      - name: Run the tests
+        run: sudo make container-unittests-el7
